### ISSUE TITLE
Saving RAM in a boot.cfg file

### ISSUE THREAD

**Issue by DrNorfolk** [dcrespo3d/ZX-ESPectrum-Wiimote#18]
Hi, dcrespo3d. 
Great project, I really like it, I serve for development.
I would like to say my wishes, suddenly you can do it.
I want the game not to save on shutdown in a file boot.cfg I like it when zx spectrum loads in its classic view. I solved this possibility in this way: I added a setting to the file Config.cpp lines 124-125
```
    #ifdef SAVE_RAM
    Serial.printf("  + ram:%s\n", ram_file.c_str());
    f.printf("ram:%s\n", ram_file.c_str());
    #endif
```
And somewhere you need to define this #define SAVE_RAM

Thank you, I will be glad if you implement this feature in future versions

**Comment by dcrespo3d** [comment]
I have #defined SNAPSHOT_LOAD_LAST, which controls saving (and **loading**) of ram file name to/from config file.
You can comment out the define in hardconfig.h.

**Comment by DrNorfolk** [comment]
dcrespo3d, Great job!
I checked, everything works!
