### ISSUE TITLE
Load TAP files

### ISSUE THREAD

**Issue by mirivlad** [dcrespo3d/ZX-ESPectrum-Wiimote#20]
Hello. Maybe I didn't understand something, but I can't upload TAP files.
Enabled SD_CARD
SNA folder at the root of the memory card
The SNA folder contains the sna, z80 and tap files
The first start takes a very long time. Apparently related to reading files inside the SNA folder.
SNA files load fine
Z80 files load fine
TAP files are displayed in the list of files, but when you try to run - nothing happens. From basic48, you can see that for a moment a message appears like save config or something similar (on a yellow background) - sorry, i cant read this, because it disappears too quickly.
Am I somehow loading TAP wrong?
PS I tried both on the tap file from the project itself, and on 2-3 of my files. The result is the same.

**Comment by dcrespo3d** [comment]
TAP files must be placed in TAP folder on top of memory card, and loaded using the "select TAP file" menu option. Then, from BASIC, LOAD "" + ENTER and F6 key to start tape.

**Comment by mirivlad** [comment]
> 

I don't see the menu option - Select Tap File. Tap folder placed in root of SD card.
![изображение](https://user-images.githubusercontent.com/742619/176929953-2f8ef705-c178-4504-9548-747cf59d03d5.png)

**Comment by mirivlad** [comment]
Now working
