### ISSUE TITLE
NO VIDEO after booting

### ISSUE THREAD

**Issue by aivar74** [dcrespo3d/ZX-ESPectrum-Wiimote#21]
Hi
I m using LILYGO® TTGO VGA32 V1.4

I was installing all files, and compilation in Visual Studio was successful. 
Upload Filesystem Image .. OK
Build was OK. 
Upload was OK. 
But VGA not showing anything. 
Terminal writes : 
Free heap after filesystem: 226024
Setting resolution to 320 x 240

And from here.. nothing happens next. No video on the screen.

Any ideas..?

Aivar

**Comment by DrNorfolk** [comment]
Hey!
check the // Video color depth section in the hardconfig.h file in the include folder
and also look at the file hardpins.h there are #define which are responsible for the desired color pins

**Comment by aivar74** [comment]
Hi !
Pins are checked.
 Then..PSRAM tried to change "False". Colordepth from 6B to 3B. But still the same. No image. 
Is the reason in VGA mode 320x240 ? I dint find how to change 360 x 200 . ?

**Comment by dcrespo3d** [comment]
Did you check the TTGo 1.4 out of the box? (prior to flashing anything)

The device comes with a example firmware with some demo. Did you power it via usb and connect it via vga to your monitor? Maybe the monitor doesn't like the graphic mode... 

If you're using a TTGo 1.4, you will need 6bits, and the stated pins. Also, don't disable PSRAM.

Is that all of the console dump? Paste the full text, not just the last lines.

**Comment by aivar74** [comment]
Hey !

I checked other exaples from FAbGL in Arduino IDE like PCEemulator and several games. All worked perfectly. 
But is wrong when I try to use ZX Spectrum exaples. 
Here is full code after build and upload.. in VidualStudio Terminal:

Retrieving maximum program size .pio\build\pico32\firmware.elf
Checking size .pio\build\pico32\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [==        ]  23.5% (used 77088 bytes from 327680 bytes)
Flash: [========= ]  94.9% (used 995470 bytes from 1048576 bytes)
Configuring upload protocol...
AVAILABLE: esp-prog, espota, esptool, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa
CURRENT: upload_protocol = esptool
Looking for upload port...
Auto-detected: COM6
Uploading .pio\build\pico32\firmware.bin
esptool.py v3.1
Serial port COM6
Connecting....
Chip is ESP32-PICO-D4 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, Embedded Flash, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 4c:75:25:a7:c3:fc
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB
Flash will be erased from 0x00001000 to 0x00005fff...
Flash will be erased from 0x00008000 to 0x00008fff...
Flash will be erased from 0x0000e000 to 0x0000ffff...
Flash will be erased from 0x00010000 to 0x00103fff...
Compressed 17104 bytes to 11191...
Writing at 0x00001000... (100 %)
Wrote 17104 bytes (11191 compressed) at 0x00001000 in 0.5 seconds (effective 255.1 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 117...
Writing at 0x00008000... (100 %)
Wrote 3072 bytes (117 compressed) at 0x00008000 in 0.1 seconds (effective 453.3 kbit/s)...
Hash of data verified.
Compressed 8192 bytes to 47...
Writing at 0x0000e000... (100 %)
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.1 seconds (effective 636.3 kbit/s)...
Hash of data verified.
Compressed 995584 bytes to 579015...
Writing at 0x00010000... (2 %)
Writing at 0x0001aacd... (5 %)
Writing at 0x0002efc2... (8 %)
Writing at 0x0003b728... (11 %)
Writing at 0x00043fb1... (13 %)
Writing at 0x0004b14a... (16 %)
Writing at 0x000548bc... (19 %)
Writing at 0x00059fdf... (22 %)
Writing at 0x0005f11f... (25 %)
Writing at 0x000643e0... (27 %)
Writing at 0x000698b2... (30 %)
Writing at 0x0006ee8e... (33 %)
Writing at 0x00074f4f... (36 %)
Writing at 0x0007d764... (38 %)
Writing at 0x00083cc1... (41 %)
Writing at 0x0008932b... (44 %)
Writing at 0x0008ea57... (47 %)
Writing at 0x000940a9... (50 %)
Writing at 0x00099a8d... (52 %)
Writing at 0x0009f92e... (55 %)
Writing at 0x000a5330... (58 %)
Writing at 0x000ab214... (61 %)
Writing at 0x000b1186... (63 %)
Writing at 0x000b6b5c... (66 %)
Writing at 0x000bd746... (69 %)
Writing at 0x000c3ab2... (72 %)
Writing at 0x000c990a... (75 %)
Writing at 0x000cfbbe... (77 %)
Writing at 0x000d5b05... (80 %)
Writing at 0x000dbbb2... (83 %)
Writing at 0x000e27d6... (86 %)
Writing at 0x000e9b4d... (88 %)
Writing at 0x000ef837... (91 %)
Writing at 0x000f5379... (94 %)
Writing at 0x000faff0... (97 %)
Writing at 0x00100b01... (100 %)
Wrote 995584 bytes (579015 compressed) at 0x00010000 in 14.1 seconds (effective 564.5 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
============================ [SUCCESS] Took 22.46 seconds ============================
--- Terminal on COM6 | 115200 8-N-1
--- Available filters and text transformations: colorize, debug, default, direct, esp32_exception_decoder, hexlify, log2file, nocontrol, printable, send_on_enter, time
--- More details at https://bit.ly/pio-monitor-filters
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
configsip: 188777542, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8
ZX-ESPectrum + Wiimote initializing...
Running on little endian CPU
Initializing VGA
PSRAM size: 4194252
Free heap at begin of setup: 231608
Free heap after wiimote: 231608
Initializing internal storage...
Loading config file '/boot.cfg':
Loading file '/boot.cfg'
  + arch: '48K'
  + romset: 'SINCLAIR'
  + ram: 'Snake.sna'
  + slog_on: 'true'
  + asp169: 'false'
Config file loaded OK
Getting entries from: '/sna'
Found FILE: /sna/diag.sna...49179b...diag.sna...ADDING
Found FILE: /sna/fantasy.sna...49179b...fantasy.sna...ADDING
Found FILE: /sna/fantasy.txt...715b...fantasy.txt...IGNORING TXT
Found FILE: /sna/ManicMiner.txt...715b...ManicMiner.txt...IGNORING TXT
Found FILE: /sna/Snake.sna...49179b...Snake.sna...ADDING
Found FILE: /sna/Snake.txt...715b...Snake.txt...IGNORING TXT
Found FILE: /sna/sppong.sna...49179b...sppong.sna...ADDING
Found FILE: /sna/sppong.txt...715b...sppong.txt...IGNORING TXT
Found FILE: /sna/Tetris.sna...49179b...Tetris.sna...ADDING
Found FILE: /sna/Tetris.txt...715b...Tetris.txt...IGNORING TXT
Getting entries from: '/tap'
Found FILE: /tap/teclado.tap...155b...teclado.tap...ADDING
Free heap after filesystem: 226024
Setting resolution to 320 x 240

**Comment by aivar74** [comment]
Hi again
it works now. I inserted into hardconfig.h statement from readme.md
//
If your monitor is 4:3, you should edit hardconfig.h, comment the `#define AR_16_9 1` line, and uncomment the `#define AR_4_3 1` line.
//

**Comment by aivar74** [comment]
> Hi again it works now. I inserted into hardconfig.h statement from readme.md // If your monitor is 4:3, you should edit hardconfig.h, comment the `#define AR_16_9 1` line, and uncomment the `#define AR_4_3 1` line. //

...
28.07.222 issue appeared again. Now tried another board and it works properly . so the problem is  in bad hardware I think.
