### ISSUE TITLE
Forgotten in the readme

### ISSUE THREAD

**Issue by jorgefuertes** [dcrespo3d/ZX-ESPectrum-Wiimote#6]
Thanks to Rampa and Queru, and references to the original project: https://github.com/rampa069/ZX-ESPectrum.

It happens.

**Comment by dcrespo3d** [comment]
Done, acknowledged both Rampa and Queru as well as the original project.

Sorry for the delay, I did a lot of work in this project in march and the forgot a bit about it.

Regards!
